# Generated by Django 4.2 on 2023-05-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruteria', '0002_purchasecart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasecart',
            old_name='estado',
            new_name='state',
        ),
    ]
